'reinit'
'sdfopen http://apdrc.soest.hawaii.edu:80/dods/public_data/CPC_Temperature/tmax'
'set lon 90 140'
'set lat -10 5'
'set time 01Jan2023 07Jan2023'
'define suhumax=tmax'
'set sdfwrite data/suhumax.nc'
'sdfwrite suhumax'
'set sdfwrite close'
